package com.example.a22b11.db;

import androidx.room.Dao;
import androidx.room.Delete;
import androidx.room.Insert;
import androidx.room.Query;

import com.google.common.util.concurrent.ListenableFuture;

import java.time.Instant;
import java.util.List;

@Dao
public interface MoodDao {
    @Query("SELECT * FROM moods")
    ListenableFuture<List<Mood>> getAll();

    @Query("SELECT * FROM moods WHERE user_id = :userId")
    ListenableFuture<List<Mood>> getAllByUserId(long userId);

    @Query("SELECT * FROM moods WHERE assessment BETWEEN :assessMin AND :assessMax ORDER BY assessment ASC")
    ListenableFuture<List<Mood>> getMoodBetween(Instant assessMin, Instant assessMax);



    /**
     * Insert a new mood
     * @param mood new mood
     * @return autogenerated local mood id
     */
    @Insert
    ListenableFuture<Void> insert(Mood mood);

    /**
     * Insert new mood
     * @param moods new moods
     * @return list of autogenerated local mood ids
     */
    @Insert
    ListenableFuture<List<Long>> insertAll(Mood... moods);

    @Delete
    ListenableFuture<Void> delete(Mood mood);
}
