package com.example.a22b11.db;

import androidx.room.Dao;
import androidx.room.Delete;
import androidx.room.Insert;
import androidx.room.Query;

import java.util.List;

@Dao
public interface MoodDao {
    @Query("SELECT * FROM moods")
    List<Mood> getAll();

    @Query("SELECT * FROM moods WHERE user_id = :userId")
    List<Mood> getAllByUserId(long userId);

    /**
     * Insert a new mood
     * @param mood new mood
     * @return autogenerated local mood id
     */
    @Insert
    long insert(Mood mood);

    /**
     * Insert new mood
     * @param moods new moods
     * @return list of autogenerated local mood ids
     */
    @Insert
    List<Long> insertAll(Mood... moods);

    @Delete
    void delete(Mood mood);
}
